import { chromium } from "playwright-core";
import path from "node:path";
import fs from "node:fs";
const WORK = process.env.WORK;
const CHROME = `${process.env.HOME}/Library/Caches/ms-playwright/chromium-1208/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing`;
const APP = "http://127.0.0.1:5190";
const DB = "http://127.0.0.1:5991";
const prof = path.join(WORK, "profile-explore");
fs.rmSync(prof, { recursive: true, force: true });
const ctx = await chromium.launchPersistentContext(prof, { executablePath: CHROME, headless: true, timezoneId: "America/New_York", viewport: { width: 1400, height: 900 } });
await ctx.clock.install({ time: new Date("2026-09-25T18:00:00-04:00") });
let page = ctx.pages()[0] || (await ctx.newPage());
page.on("console", (m) => { if (["error", "warning"].includes(m.type())) console.log("[console]", m.type(), m.text().slice(0, 200)); });
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
page.on("dialog", (d) => { console.log("[dialog]", d.message()); d.accept(); });
await page.goto(APP);
console.log("page time:", await page.evaluate(() => new Date().toString()));
await page.fill('input[type="email"]', "explore@example.com");
await page.click('button:has-text("Send login link")');
await page.waitForSelector("text=Check your inbox", { timeout: 10000 });
const magic = await (await fetch(`${DB}/__magic`)).json();
const link = magic.filter((m) => m.email === "explore@example.com").at(-1).link;
console.log("link:", link);
await page.goto(link);
await page.waitForTimeout(3000);
console.log("url after:", page.url());
console.log("body:", (await page.evaluate(() => document.body.innerText)).slice(0, 600));
// clock jump + new page
await ctx.clock.setSystemTime(new Date("2026-09-26T09:00:00-04:00"));
await page.close();
page = await ctx.newPage();
await page.goto(APP);
await page.waitForTimeout(3000);
console.log("page time after jump:", await page.evaluate(() => new Date().toString()));
console.log("body2:", (await page.evaluate(() => document.body.innerText)).slice(0, 300));
const t0 = await page.evaluate(() => Date.now());
await page.clock.fastForward(8000);
const t1 = await page.evaluate(() => Date.now());
console.log("fastForward delta ms:", t1 - t0);
const ls = await page.evaluate(() => Object.keys(localStorage));
console.log("localStorage keys:", ls);
await ctx.close();
