// Cards for the classes dated after RAW's last date (2026-04-07), written by
// hand from each block's text, following the parser's own rules
// (WHAT_BECOMES_A_CARD): every real French word, expression or example
// sentence becomes a "V" card with its English meaning; rules ("Articles :
// définis : le, la, les", "de + le = du") produce nothing; French kept exactly
// as written (notebook apostrophes included) except a word the grammar
// requires, which is restored (rule 10d); no final full stop (rule 10e).
// `kind` is the item's true nature for the hidden memory model (vocab or expr);
// it is NOT sent to the app, which only ever sees V or G.
export const HANDWRITTEN = {
  "2026-04-14": [
    ["s’endormir", "to fall asleep", "vocab"],
    ["le raccourci", "the shortcut", "vocab"],
    ["porter", "to carry / to wear", "vocab"],
    ["lourd, lourde (adj)", "heavy", "vocab"],
    ["se concentrer sur", "to focus on", "vocab"],
    ["faire un pari", "to make a bet", "vocab"],
    ["culpabiliser", "to feel guilty", "vocab"],
    ["vexé (adj)", "offended / hurt", "vocab"],
    ["On peut recommencer l’exercice au début", "We can start the exercise again from the beginning", "expr"],
    ["on a découvert", "we discovered", "expr"],
    ["je me suis fait mal au dos", "I hurt my back", "expr"],
    ["je l’ai revu", "I saw him again", "expr"],
    ["tu nous dois une margarita", "you owe us a margarita", "expr"],
    ["je n’ai pas envie d’aller à cette date", "I don't feel like going on that date", "expr"],
    ["le mieux du mieux", "the very best", "expr"],
    ["un problème de communication sur l’heure", "a miscommunication about the time", "expr"],
    ["même avant de la rencontrer", "even before meeting her", "expr"],
    ["je dois savoir ce que je te dois", "I need to know what I owe you", "expr"],
    ["Amuse-toi bien !", "Have fun!", "expr"],
    ["les courses", "the groceries / the shopping", "vocab"],
    ["Elle s’est endormi", "She fell asleep", "expr"],
    ["il s’est coupé le doigt", "he cut his finger", "expr"],
    ["je me suis cassé la jambe", "I broke my leg", "expr"],
    ["les vieilles photos", "the old photos", "vocab"],
    ["j’ai de l’argent", "I have (some) money", "expr"],
    ["j’ai beaucoup d’argent", "I have a lot of money", "expr"],
    ["je bois de l’eau", "I drink (some) water", "expr"],
    ["je mange de la viande", "I eat (some) meat", "expr"],
    ["je mange du pain", "I eat (some) bread", "expr"],
  ],
  "2026-04-13": [
    ["télécharger", "to download", "vocab"],
    ["faire des économies", "to save money", "vocab"],
    ["faire attention", "to pay attention / to be careful", "vocab"],
    ["en-bas", "downstairs / down below", "vocab"],
    ["descendre", "to go down", "vocab"],
    ["abîmer", "to damage", "vocab"],
    ["un écran", "a screen", "vocab"],
    ["dans le noir", "in the dark", "vocab"],
    ["tu l’as rendu ?", "did you give it back?", "expr"],
    ["à voix haute", "out loud", "expr"],
    ["si j’ai quelque chose dans la tête", "if I have something on my mind", "expr"],
  ],
  "2026-04-10": [
    ["un poste", "a position / a job", "vocab"],
    ["fonder / créer une entreprise", "to found / to start a company", "vocab"],
    ["une option", "an option", "vocab"],
    ["décorer", "to decorate", "vocab"],
    ["une somme d’argent", "a sum of money", "vocab"],
    ["investir", "to invest", "vocab"],
    ["un deal", "a deal", "vocab"],
    ["rentable (adj)", "profitable", "vocab"],
    ["être coté en bourse", "to be listed on the stock exchange", "vocab"],
    ["un compte", "an account", "vocab"],
    ["les humains", "humans", "vocab"],
    ["seulement une page", "only one page", "expr"],
    ["Tu dois le rendre quand ?", "When do you have to hand it in?", "expr"],
    ["c’est devenu", "it became", "expr"],
    ["l’équipe voulait tellement faire des ventes", "the team wanted so badly to make sales", "expr"],
    ["ce qui se passe", "what is happening", "expr"],
    ["ce qui s’est passé", "what happened", "expr"],
    ["ce qui allait se passer", "what was going to happen", "expr"],
    ["je suis jamais allé", "I've never been", "expr"],
    ["le mec avec qui je parlais", "the guy I was talking to", "expr"],
    ["il y en a 2", "there are 2 (of them)", "expr"],
    ["tu le loues", "you rent it", "expr"],
  ],
  "2026-04-09": [
    ["technique (adj)", "technical", "vocab"],
    ["techniquement (adv)", "technically", "vocab"],
    ["faire du télétravail", "to work remotely", "vocab"],
    ["exiger", "to demand / to require", "vocab"],
    ["l’économie", "the economy", "vocab"],
    ["faire payer", "to charge (money)", "vocab"],
    ["l’immobilier", "real estate", "vocab"],
    ["risqué (adj)", "risky", "vocab"],
    ["rentable (adj)", "profitable", "vocab"],
    ["il attendait pas beaucoup de moi", "he didn't expect much from me", "expr"],
    ["je connais le sujet plutôt bien", "I know the subject pretty well", "expr"],
    ["il était très direct", "he was very direct", "expr"],
    ["il y a des choses qui se recoupent", "there are things that overlap", "expr"],
    ["ils paient très bien", "they pay very well", "expr"],
    ["ils fonctionnent encore", "they still work", "expr"],
    ["je l’ai bien aimé", "I really liked it", "expr"],
    ["ils ont exigé que leurs employés reviennent au travail", "they demanded that their employees come back to work", "expr"],
  ],
  "2026-04-08": [
    ["un effet secondaire", "a side effect", "vocab"],
    ["un médicament", "a medication / a drug", "vocab"],
    ["le traitement", "the treatment", "vocab"],
    ["un changement", "a change", "vocab"],
    ["digérer", "to digest", "vocab"],
    ["se comporter", "to behave", "vocab"],
    ["accepter", "to accept", "vocab"],
    ["tolérer", "to tolerate", "vocab"],
    ["le compte à rebour", "the countdown", "vocab"],
    ["tomber enceinte", "to get pregnant", "vocab"],
    ["un pervers narcissique", "a narcissistic manipulator", "vocab"],
    ["anxieux (adj)", "anxious", "vocab"],
    ["évitant (adj)", "avoidant", "vocab"],
    ["un niveau", "a level", "vocab"],
    ["s’attaquer à", "to tackle", "vocab"],
    ["les deux premières semaines", "the first two weeks", "expr"],
    ["prendre des médicaments", "to take medication", "expr"],
    ["ce n’est pas sain", "it's not healthy", "expr"],
    ["j’ai su ce que je devais faire à ce moment-là", "I knew what I had to do at that moment", "expr"],
    ["elle devait", "she had to / she was supposed to", "expr"],
    ["elle devrait", "she should", "expr"],
    ["quand je me vois me comporter comme un anxieux", "when I see myself behaving like an anxious person", "expr"],
    ["j’ai confiance en moi", "I'm confident in myself", "expr"],
    ["je vais y penser", "I'll think about it", "expr"],
    ["Elle le prend depuis 3 semaines", "She has been taking it for 3 weeks", "expr"],
    ["Il n’y a plus rien à digérer", "There's nothing left to digest", "expr"],
    ["Elle s’est pas comportée comme ça avant", "She didn't behave like that before", "expr"],
  ],
};
